#-------------------------------
# Site Settings
title: START ACADEMIA
description: Start Academia is a company dedicated to education and innovation.
logo: #'/images/logo.png'
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: light # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Programs'
      url: '/programs/'
    - title: 'Impact'
      url: '/impact/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'



#-------------------------------
# Author Settings
author:
  author_name: Start Academia Team
  author_avatar: /images/01-1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: 
  hero_title: Hi Starters! ðŸ‘‹
  hero_subtitle: We are Start Academia, here we design innovative learning experiences for schools, educators, and students.
  hero_description: |
    We help institutions adapt to the digital era through strategic training, technology integration, and personalized learning design.
  hero_image: /images/01-3.jpg
  hero_image_caption: My creative space, where masterpieces are born
  hero_button_text: Letâ€™s Work Together
  hero_button_link: '/contact/'


# Logos
logos:
  enable: false
  logos_title: Trusted by Innovative Schools and Partners
  logo_image:
    - alt: "Game Boy"
      image: "/images/1000.jpg"
    - alt: "Super Nintendo"
      image: "/images/1001.jpg"
    - alt: "Keyboard"
      image: "/images/1002.jpg"
    - alt: "Headphones"
      image: "/images/1003.jpg"
    - alt: "Mouse"
      image: "/images/1004.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: Our Programs and Team


#-------------------------------
# Tags Section Settings
tags_section:
  enable: false
  tags_section_title: Hackerâ€™s Haven
  tags:
    - tag: "Programming"
      image: "/images/20.jpg"
    - tag: "Linux"
      image: "/images/21.jpg"
    - tag: "Productivity"
      image: "/images/22.jpg"
    - tag: "Security"
      image: "/images/23.jpg"


#-------------------------------
# Videos Section Settings
videos_section:
  enable: true
  videos_section_title: Our Work in Action


#-------------------------------
# Gallery Section Settings
gallery_section:
  enable: true
  gallery_section_title: Our Gallery
  gallery:
    gallery_images:
      - alt: 'Rest'
        url: '/images/100.jpg'
        caption: 'Small steps lead to big results.'
      - alt: 'Lifestyle'
        url: '/images/101.jpg'
        caption: 'A peaceful moment captured during a serene evening.'
      - alt: 'Hobby'
        url: '/images/102.jpg'
        caption: 'True friends are like stars â€” they shine brightest when the world feels dark.'
      - alt: 'Computers'
        url: '/images/103.jpg'
        caption: 'Every click opens a new chapter in an endless story.'
      - alt: 'Games'
        url: '/images/104.jpg'
        caption: 'Every level is a new opportunity to test your limits.'


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Join the Start Academia Network ðŸ’¡
  mailchimp_description: Stay updated on educational innovation, leadership programs, and opportunities to collaborate.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address...
  mailchimp_button_text: Join Now


#-------------------------------
# Footer Settings
footer_description: We are Start Academia, here we design innovative learning experiences for schools, educators, and students. We help institutions adapt to the digital era through strategic training, technology integration, and personalized learning design.



#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://linkedin.com/company/startacademia"}
- {icon: "fa-brands fa-youtube", name: "YouTube", link: "https://youtube.com/@startacademia"}
- {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com/startacademia"}
- {icon: "fa-solid fa-envelope", name: "Email", link: "mailto:contact@startacademia.org"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: your@email.com # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id